homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude

  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  # Customization file
  customize: !include customize.yaml
  
http:
  base_url: !secret base_url

# Enables the frontend
frontend:
  themes: !include themes.yaml
  extra_html_url:
  - /local/custom_ui/state-card-floorplan.html

# Enables configuration UI
config:

device_tracker:
  - platform: gpslogger
  - platform: nmap_tracker
    hosts:
    - !secret ip_sander
    - !secret ip_naomi
    interval_seconds: 30

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: !secret url_configurator
  pihole:
    title: Pi-hole
    icon: mdi:block-helper
    url: !secret url_pihole
  calendar:
    title: Kalender
    icon: mdi:calendar
    url: !secret url_calendar

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

weather:
  - platform: buienradar
    name: buienradar

sensor: !include sensors.yaml

# Text to speech
tts:
  - platform: google
  
notify:
  - platform: html5
    gcm_api_key: !secret notify_api_key
    gcm_sender_id: !secret notify_sender_id
  
media_player: !include media_players.yaml
    
google_assistant:
  project_id: !secret google_project_id
  api_key: !secret google_api_key
  exposed_domains:
    - media_player
    - group
    - input_boolean
    - switch

# Cloud
#cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
switch: !include switches.yaml
zone: !include zones.yaml