homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude

  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam

  packages: !include_dir_named packages
  
logger:
  default: error
  
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - ::1
  ip_ban_enabled: True
  login_attempts_threshold: 5
  base_url: !secret base_url

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes
  extra_html_url:
    - /local/custom_ui/state-card-custom-ui.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-custom-ui-es5.html

lovelace:
  mode: yaml

customizer:
  custom_ui: local

# Enables configuration UI
#config:

system_health:

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true
  
custom_updater:
  show_installable: true
  track:
    - components
    - cards
    - python_scripts
  card_urls:
    - https://raw.githubusercontent.com/bramkragten/custom-ui/master/updater.json
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json
    - https://raw.githubusercontent.com/kalkih/simple-weather-card/master/tracker.json
    - https://raw.githubusercontent.com/ljmerza/calendar-card/master/custom_updater.json
    - https://raw.githubusercontent.com/nervetattoo/simple-thermostat/master/tracker.json
    - https://raw.githubusercontent.com/atomic7777/atomic_calendar/master/tracker.json
    - https://raw.githubusercontent.com/kuuji/button-card/master/tracker.json
  component_urls:
    - https://raw.githubusercontent.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/master/custom_components.json

hassio:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time
history:
  include:
    domains:
      - switch
      - media_player
      - binary_sensor
    entities:
      - device_tracker.his_phone
      - device_tracker.her_phone
  exclude:
    entities:
      - binary_sensor.morning
      - binary_sensor.evening
      - binary_sensor.floorplan
      - binary_sensor.laptop_state
      - switch.news_rtl
      - switch.news_nos
  

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

mqtt:
  broker: core-mosquitto
  username: !secret mosquitto_username
  password: !secret mosquitto_password

rflink:
  port: /dev/ttyUSB0
      
ifttt:
  key: !secret ifttt_key

zone: !include zones.yaml