- platform: samsungtv
  host: !secret ip_samsung_tv
  mac: !secret mac_samsung_tv
  name: samsungtv
  
- platform: xboxone
  device: !secret xbox_id
  name: Xbox
  
- platform: harman_kardon_avr
  host: !secret ip_avr
  
- platform: harman_kardon_avr_test
  host: !secret ip_avr
  
- platform: horizon
  host: !secret ip_horizon
  name: Horizon
  
- platform: spotify
  name: Spotify
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret