resources:
  - url: /local/tracker-card.js?v=0.1.5
    type: js
  - url: /local/custom_ui/mini-media-player-bundle.js?v=0.9.2
    type: module
  - url: /local/custom_ui/weather-card.js
    type: js
  - url: /local/custom-lovelace/group-card/group-card.js?v=0.0.2
    type: js

views:
  - title: Home
    icon: mdi:home-outline
    badges:
    - sun.sun
    - device_tracker.sander
    - device_tracker.naomi
    - sensor.yr_symbol
    cards:
      - type: glance
        title: Lights
        show_state: false
        entities:
          - entity: switch.lampen_woonkamer
            name: Alle
            icon: mdi:lightbulb
            tap_action: toggle
          - entity: switch.bank
            name: Bank rechts
            icon: mdi:desk-lamp
            tap_action: toggle
      - type: conditional
        conditions:
          - entity: media_player.horizon
            state_not: off
          - entity: media_player.horizon
            state_not: unavailable
        card:
          type: media-control
          entity: media_player.horizon
      - type: custom:mini-media-player
        title: Harman Kardon
        entity: media_player.harman_kardon_avr
        icon: mdi:surround-sound
        artwork_border: true
        show_source: true
        volume_stateless: true
        
  - title: Media
    icon: mdi:cellphone-link
    cards:
      - type: entities
        title: Woonkamer
        entities:
          - entity: media_player.harman_kardon_avr
            type: custom:mini-media-player
            icon: mdi:surround-sound
            group: true
            hide_controls: true
            show_source: true
            volume_stateless: true
            power_color: true
          - entity: media_player.horizon
            type: custom:mini-media-player
            icon: mdi:television-box
            show_source: true
            hide_volume: true
            hide_mute: true
            group: true
            power_color: true
          - entity: media_player.samsungtv
            type: custom:mini-media-player
            icon: mdi:television
            hide_controls: true
            group: true
            power_color: true
            hide_volume: true
          - entity: media_player.xbox
            icon: mdi:xbox
            type: custom:mini-media-player
            hide_controls: true
            show_source: true
            group: true
            power_color: true
            hide_volume: true
            
      - type: media-control
        entity: media_player.spotify
  
  - title: Overig
    garage_door_tilt_sensor_alarm_level: Weather
    cards:
      - type: custom:weather-card
        entity_weather: weather.buienradar
        entity_sun: sun.sun
      - type: custom:group-card
        card:
          title: Wie is waar
          type: entities
        group: group.tracked_devices
      - type: custom:group-card
        title:
        card:
          type: glance
        group: group.trains
        
  - title: Tests
    cards:
      - type: glance
        entities:
          - entity: light.living_room
      - type: custom:mini-media-player
        title: Harman Kardon
        entity: media_player.harman_kardon_avr_test
        icon: mdi:surround-sound
        artwork_border: true
        show_source: true
        volume_stateless: true
          
  - title: Configuration
    icon: mdi:settings
    cards:
      - type: custom:tracker-card
        title:
        trackers:
          - sensor.custom_card_tracker
          - sensor.custom_component_tracker
