#########################################
# General configuration
#########################################

panel_iframe:
  ide:
    title: IDE
    icon: mdi:cloud-tags
    url: !secret url_ide
  calendar:
    title: Kalender
    icon: mdi:calendar
    url: !secret url_calendar
  bitwarden:
    title: Bitwarden
    icon: mdi:safe
    url: !secret url_bitwarden

automation:

  - alias: Set default theme on startup
    initial_state: 'on'
    trigger:
    - platform: homeassistant
      event: start
    action:
    - service: frontend.set_theme
      data:
        name: dark_theme

  - id: theme_automatic
    alias: Automatic Theme Change
    initial_state: on
    trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: sun.sun
      to: above_horizon
    - platform: state
      entity_id: sun.sun
      to: below_horizon
    action:
    - service_template: frontend.set_theme
      data_template:
        name: "{% if states.sun.sun.state == \"above_horizon\" %}\n  light_green\n{%\
          \ else %}\n  midnight\n{% endif %}\n"

  - id: notify_update
    alias: Update Available Notifications
    initial_state: on
    trigger:
      platform: state
      entity_id: updater.updater
    action:
      service: notify.chrome_push
      data:
        target: his_phone
        message: Update for Home Assistant is available.