light:
  - platform: rflink
    automatic_add: false
    device_defaults:
      fire_event: true
      signal_repetitions: 4
    devices:
      newkaku_02e0bc00_2:
        name: SwitchOne
        type: switchable
      newkaku_02e0bc00_3:
        name: Woonkamer Bank
        type: switchable
      newkaku_02e0bc00_4:
        name: SwitchTwo
        type: switchable
        
switch:
  - platform: rflink
    automatic_add: true
    device_defaults:
      fire_event: true
      signal_repetitions: 4

group:
  lights_livingroom:
    name: Alle Lampen Woonkamer
    entities:
      - light.living_room
      - light.woonkamer_bank
  lights_livingroom_default:
    name: Lampen Woonkamer
    entities:
      - light.stalamp
      - light.woonkamer_bank

automation:
  - id: light_evening
    alias: Light on in the evening
    initial_state: off
    trigger:
      - event: sunset
        platform: sun
      - entity_id: group.tracked_people
        platform: state
        to: home
    condition:
      - condition: state
        entity_id: group.tracked_people
        state: home
      - condition: state
        entity_id: sun.sun
        state: below_horizon
    action:
      service: light.turn_on
      entity_id: group.lights_livingroom_default
