#########################################################################
# People
#########################################################################

homeassistant:
  customize:
    switch.sleeping:
      icon: mdi:sleep
    switch.vacation:
      icon: mdi:airplane
    switch.guests:
      icon: mdi:human-male-female
  customize_glob:
    device_tracker.*:
      state_card_mode: badges
      templates:
        theme: >
          if (state) return state.toLowerCase(); else return null;

person:
  - name: Sander
    id: sander
    user_id: !secret his_user_id
    device_trackers:
      - device_tracker.his_phone
  - name: Naomi
    id: naomi
    user_id: !secret her_user_id
    device_trackers:
      - device_tracker.her_phone
  - name: Owen
    id: owen

device_tracker:
  #- platform: gpslogger
  - platform: nmap_tracker
    hosts:
    - !secret ip_his
    - !secret ip_hers
    consider_home: 600
    interval_seconds: 15
    
input_select:
  owen:
    name: Waar is Owen
    options:
      - Thuis
      - Oma
      - Snoopy
      - Anders

group:
  # People states.
  people:
    - person.sander
    - person.naomi
    - switch.sleeping
    - switch.vacation
    - switch.guests
  # Tracked people (subset of device_tracker.all_devices).
  tracked_people:
    - person.sander
    - person.naomi

switch:
  # Switch indicating sleeping.
  - platform: mqtt
    name: "Sleeping"
    state_topic: "nfc/sleeping"
    command_topic: "nfc/sleeping"
    qos: 1
    payload_on: "yes"
    payload_off: "no"
    retain: true
  # Switch indicating vacation.
  - platform: mqtt
    name: "Vacation"
    state_topic: "nfc/vacation"
    command_topic: "nfc/vacation"
    qos: 1
    payload_on: "yes"
    payload_off: "no"
    retain: true
  # Switch indicating guests.
  - platform: mqtt
    name: "Guests"
    state_topic: "nfc/guests"
    command_topic: "nfc/guests"
    qos: 1
    payload_on: "yes"
    payload_off: "no"
    retain: true
    
script:
  leave_house:
    alias: Verlaat huis
    sequence:
      - service: homeassistant.turn_off
        entity_id:
          - group.all_lights
          - group.media
      - service: script.speak
        data:
          message: 'Ik schakel alles uit, tot ziens'

automation:
  
  # Automatically turn off all devices when away for more than 30 minutes
  - id: away_mode
    alias: Away Mode
    initial_state: off
    trigger:
      platform: state
      entity_id: group.tracked_people
      to: not_home
      for:
        minutes: 30
    action:
      - service: light.turn_off
        entity_id: group.all_lights
      - service: media_player.turn_off
        entity_id: group.media

  # On vacation, make sure the thermostat is on "away" mode.
  - id: vacation_mode
    alias: Vacation started
    initial_state: on
    trigger:
      platform: state
      entity_id: switch.vacation
      to: 'on'
    action:

  # When sleeping, play a good night TTS message, turn off
  # all lighting, turn on stair nightlight lighting, turn off
  # smart sockets, pause media, and lock the front door.
  # If any door is open, don't activate.
  # If temperature meets a threshold, turn on the bedroom fan.
  - alias: Sleeping
    id: sleep_mode
    initial_state: on
    trigger:
      platform: state
      entity_id: switch.sleeping
      to: 'on'
    condition:
      - condition: state
        entity_id: switch.guests
        state: 'off'
    action:
      - service: script.turn_on
        entity_id: script.speak
        data:
          message: "Good night."
      - service: light.turn_off
        entity_id: group.all_lights
      - service: media_player.turn_off
        entity_id: group.media

  # Sleep mode isn't always manually turned off in the morning.
  # Just turn it off automatically.
  - id: awake_mode
    alias: Turn off sleep mode automatically
    initial_state: on
    trigger:
      platform: time
      at: '10:00:00'
    condition:
    - condition: state
      entity_id: switch.sleeping
      state: 'on'
    action:
      service: homeassistant.turn_off
      data:
        entity_id: switch.sleeping

  # If no one has been home for 24 hours, automatically
  # enable vacation mode.
  - id: automatic_vacation_mode
    alias: automatic vacation mode
    initial_state: on
    trigger:
      - platform: state
        entity_id: group.tracked_people
        to: not_home
        for:
          hours: 24
    action:
      - service: switch.turn_on
        entity_id: switch.vacation

  # Turn off vacation mode as soon as anyone gets home.
  - id: turn_off_vacation_mode
    alias: turn off vacation mode
    initial_state: on
    trigger:
      - platform: state
        entity_id: group.tracked_people
        to: home
    action:
      - service: switch.turn_off
        entity_id: switch.vacation