homeassistant:
  customize:
    script.play_radio:
      friendly_name: Start Playing
      icon: mdi:play

group:
  radio:
    name: Radio
    entities:
    - input_select.radio_station
    - input_boolean.play_radio
    - input_number.volume_radio
    
input_boolean:
  play_radio:
    name: Radio
    initial: off
    icon: mdi:play

input_select:
  radio_station:
    name: 'Select Radio Station:'
    options:
      - Radio 538
      - Q-Music
      - 3FM
      - 100% NL
      - Veronica
      - Sky Radio
      - Arrow Classic Rock
      - Classic FM
      - BNR Nieuwsradio
      - SLAM! Hardstyle
      - Sleep Radio
      - Ambient Sleeping Pill
      - Radio Art - Sleep
      - Ambi Nature Radio
      - Calm Radio - Sleep
      - Dinamo.FM Sleep

input_number: 
  volume_radio:
    name: Volume
    icon: mdi:volume-high
    min: 0
    max: 1
    step: 0.05 
    initial: '0.70'
  
script:

  play_radio:
    alias: Play Radio on Chromecast Audio
    sequence:
      - service: script.turn_on_receiver
      - service: media_player.volume_set
        data:
          entity_id: media_player.chromecast
          volume_level: '0.70'
      - service: media_player.play_media
        data_template:
          entity_id: media_player.chromecast
          media_content_id: >
            {% if is_state("input_select.radio_station", "Radio 538") %} http://18973.live.streamtheworld.com/RADIO538.mp3
            {% elif is_state("input_select.radio_station", "Q-Music") %} http://icecast-qmusic.cdp.triple-it.nl/Qmusic_nl_live_96.mp3
            {% elif is_state("input_select.radio_station", "3FM") %} http://icecast.omroep.nl/3fm-bb-mp3
            {% elif is_state("input_select.radio_station", "100% NL") %} http://stream.100p.nl/100pctnl.mp3
            {% elif is_state("input_select.radio_station", "Veronica") %} http://8543.live.streamtheworld.com/VERONICACMP3
            {% elif is_state("input_select.radio_station", "Sky Radio") %} http://8623.live.streamtheworld.com:80/SKYRADIOAAC_SC
            {% elif is_state("input_select.radio_station", "Arrow Classic Rock") %} http://91.221.151.155/listen.mp3
            {% elif is_state("input_select.radio_station", "Classic FM") %} http://19143.live.streamtheworld.com/CLASSICFM_SC
            {% elif is_state("input_select.radio_station", "BNR Nieuwsradio") %} http://icecast-bnr.cdp.triple-it.nl/bnr_mp3_96_03
            {% elif is_state("input_select.radio_station", "SLAM! Hardstyle") %} http://vip-icecast.538.lw.triple-it.nl/WEB17_MP3
            {% elif is_state("input_select.radio_station", "Sleep Radio") %} http://37.59.28.208:8722/stream
            {% elif is_state("input_select.radio_station", "Ambient Sleeping Pill") %} http://perseus.shoutca.st:8447/h
            {% elif is_state("input_select.radio_station", "Radio Art - Sleep") %} http://live.radioart.com/fSleep.mp3
            {% elif is_state("input_select.radio_station", "Ambi Nature Radio") %} http://94.23.252.14:8067/stream
            {% elif is_state("input_select.radio_station", "Calm Radio - Sleep") %} http://streams.calmradio.com/api/39/128/stream
            {% elif is_state("input_select.radio_station", "Dinamo.FM Sleep") %} http://channels.dinamo.fm/sleep-aac
            {% endif %}
          media_content_type: 'audio/mp4'

automation:
  - id: radio_play
    alias: Listen Radio
    initial_state: on
    trigger:
      - platform: state
        entity_id: input_select.radio_station
      - platform: state
        entity_id: input_boolean.play_radio
        to: 'on'
    action: 
      - service: script.play_radio
  - id: radio_off
    alias: Stop Radio
    initial_state: on
    trigger:
      - platform: state
        entity_id: input_boolean.play_radio
        to: 'off'
    action:
      - service: media_player.turn_off
        data:
          entity_id: media_player.chromecast
  - id: radio_volume
    alias: 'Set Radio Volume'
    initial_state: on
    trigger:
      platform: state
      entity_id: input_number.volume_radio
    action:
      service: media_player.volume_set
      data_template:
        entity_id: media_player.chromecast
        volume_level: '{{ states.input_number.volume_radio.state }}'