group:

  trains:
    name: Treinen
    entities:
      - sensor.ossevelddeventer
      - sensor.deventerosseveld
      
  train_deventer:
    name: Trein Werk
    entities:
      - sensor.ossevelddeventer
      
  train_apeldoorn:
    name: Trein Huis
    entities:
      - sensor.deventerosseveld

sensor:
  - platform: nederlandse_spoorwegen
    name: "Treinen"
    email: !secret ns_user
    password: !secret ns_password
    routes:
      - name: Osseveld-Deventer
        from: Apdo
        to: Dv
      - name: Deventer-Osseveld
        from: Dv
        to: Apdo